apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: voting
spec:
  minReadySeconds: 10
  replicas: 0
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: docker.pkg.github.com/atix-ag/voting-app-code/worker
        name: worker
        envFrom:
        - prefix: POSTGRES_
          secretRef:
            name: db-secret
