---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: vote
  name: vote
  namespace: voting
spec:
  rules:
  - host: vote.voting.atix-training.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 8080
  tls:
  - hosts:
    - vote.voting.atix-training.de
    secretName: tls
...
