---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: redis
  labels:
    app: redis
    component: database
    part-of: load
  namespace: load
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    app: redis
    component: database
    part-of: load
...
