apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-controller
  labels:
    app: redis
    component: db
data:
  entrypoint.sh: |
    export PATH=$PATH:/root/go/bin
    redis-server /redis.conf &
    go get github.com/sarweshsuman/redis-cluster-go-coordinator
    redis-cluster-go-coordinator
  redis.conf: |
    bind 0.0.0.0
    port 6379
    appendonly yes
  install.sh: |
    apk add bash \
        sed \
        git \
        go
    apk add --update redis
    sh entrypoint.sh
