apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  labels:
    app: redis
    component: db
data:
  entrypoint.sh: |
    function launchredis() {
      echo "Launching Redis instance"
      HOSTNAME=`hostname -i`
      echo "Registering my Hostname" $HOSTNAME " with coordinator service"
      echo "Coordination Service Host "$REDIS_CLUSTER_COORDINATOR_SERVICE_SERVICE_HOST
      echo "Coordination Service Port "$REDIS_CLUSTER_COORDINATOR_SERVICE_SERVICE_PORT
      redis-cli -h $REDIS_CLUSTER_COORDINATOR_SERVICE_SERVICE_HOST -p $REDIS_CLUSTER_COORDINATOR_SERVICE_SERVICE_PORT lpush REDIS_CLUSTER_REGISTRATION_QUEUE "$HOSTNAME:6379"
      redis-server /redis.conf --protected-mode no
    }
    launchredis
  redis.conf: |
    bind 0.0.0.0
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
