---
# Source: redis-cluster/templates/redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: foo
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
  selector:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: foo
...
